name: Tägliches IPTV Update

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:      # Manual start

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Repository laden
      uses: actions/checkout@v3

    - name: Python einrichten
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Tools installieren
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp requests

    - name: Skript ausführen
      run: python update.py

    - name: Änderungen speichern
      run: |
        git config --global user.name "Auto-Bot"
        git config --global user.email "bot@github.com"
        
        git add turkalmankanallari.m3u
        
        git rm --cached turk_kanallari.m3u || true
        
        git commit -m "Auto-Update: turkalmankanallari.m3u" || echo "Keine Änderungen"
        git push
